import profilePic from '@/assets/DashboardAssets/dummyImg.avif';

const LiFiMentors = [
  {
    name: 'Ananya Sharma',
    category: 'TECHNOLOGY',
    company: 'TechNova Solutions',
    skills: ['React', 'JavaScript', 'Node.js', 'System Design','Mindfulness'],
    socials: {
      instagram: 'https://instagram.com/ananyasharma',
      twitter: 'https://twitter.com/ananyatech',
      linkedin: 'https://linkedin.com/in/ananyasharma',
      github: 'https://github.com/ananyasharma',
    },
    profile_picture: profilePic,
  },
  {
    name: 'Rahul Mehta',
    category: 'BUSINESS',
    company: 'BizSpark India',
    skills: ['Startups', 'Fundraising', 'Marketing Strategy','Mindfulness','Mindfulness','Mindfulness','Mindfulness'],
    socials: {
      instagram: 'https://instagram.com/rahulmehta',
      twitter: 'https://twitter.com/rahul_biz',
      linkedin: 'https://linkedin.com/in/rahulmehta',
      github: '',
    },
    profile_picture: profilePic,
  },
  {
    name: 'Deepika Verma',
    category: 'HEALTH & FITNESS',
    company: 'FitWell Studio',
    skills: ['Yoga', 'Nutrition', 'Mindfulness'],
    socials: {
      instagram: 'https://instagram.com/deepikafit',
      twitter: '',
      linkedin: 'https://linkedin.com/in/deepikaverma',
      github: '',
    },
    profile_picture: profilePic,
  },
  {
    name: 'Swami Gyanananda',
    category: 'SPIRITUALITY',
    company: 'Gyan Ashram',
    skills: ['Meditation', 'Vedanta', 'Spiritual Counseling'],
    socials: {
      instagram: 'https://instagram.com/gyanananda',
      twitter: 'https://twitter.com/swami_gyan',
      linkedin: '',
      github: '',
    },
    profile_picture: profilePic,
  },
  {
    name: 'Ishaan Roy',
    category: 'TECHNOLOGY',
    company: 'CodeBase Labs',
    skills: ['Python', 'Machine Learning', 'Django'],
    socials: {
      instagram: '',
      twitter: 'https://twitter.com/ishaan_codes',
      linkedin: 'https://linkedin.com/in/ishaanroy',
      github: 'https://github.com/ishaanroy',
    },
    profile_picture: profilePic,
  },
  {
    name: 'Meera Nair',
    category: 'BUSINESS',
    company: 'Elevate HR',
    skills: ['HR Consulting', 'Leadership', 'Diversity & Inclusion'],
    socials: {
      instagram: 'https://instagram.com/meeranair',
      twitter: '',
      linkedin: 'https://linkedin.com/in/meeranair',
      github: '',
    },
    profile_picture: profilePic,
  },
  {
    name: 'Karan Deshmukh',
    category: 'TECHNOLOGY',
    company: 'CloudXpert',
    skills: ['AWS', 'DevOps', 'CI/CD', 'Docker'],
    socials: {
      instagram: '',
      twitter: 'https://twitter.com/devkaran',
      linkedin: 'https://linkedin.com/in/karandeshmukh',
      github: 'https://github.com/karandev',
    },
    profile_picture: profilePic,
  },
  {
    name: 'Pooja Sinha',
    category: 'HEALTH & FITNESS',
    company: 'NutritionWorks',
    skills: ['Diet Planning', 'Weight Loss', 'Holistic Health'],
    socials: {
      instagram: 'https://instagram.com/poojafit',
      twitter: '',
      linkedin: 'https://linkedin.com/in/poojasinha',
      github: '',
    },
    profile_picture: profilePic,
  },
  {
    name: 'Aman Chauhan',
    category: 'SPIRITUALITY',
    company: 'InnerPath',
    skills: ['Kundalini Yoga', 'Chakra Healing', 'Mindful Living'],
    socials: {
      instagram: 'https://instagram.com/amanchauhan',
      twitter: 'https://twitter.com/spirit_aman',
      linkedin: '',
      github: '',
    },
    profile_picture: profilePic,
  },
  {
    name: 'Ritika Kapoor',
    category: 'TECHNOLOGY',
    company: 'DataCrux',
    skills: ['SQL', 'Data Visualization', 'Power BI'],
    socials: {
      instagram: '',
      twitter: '',
      linkedin: 'https://linkedin.com/in/ritikakapoor',
      github: 'https://github.com/ritikadata',
    },
    profile_picture: profilePic,
  },
  {
    name: 'Naveen Bhatia',
    category: 'BUSINESS',
    company: 'RetailVerse',
    skills: ['E-commerce', 'Supply Chain', 'Customer Experience'],
    socials: {
      instagram: 'https://instagram.com/naveenbiz',
      twitter: 'https://twitter.com/naveenretail',
      linkedin: 'https://linkedin.com/in/naveenbhatia',
      github: '',
    },
    profile_picture: profilePic,
  },
  {
    name: 'Lakshmi Menon',
    category: 'HEALTH & FITNESS',
    company: 'Wellness360',
    skills: ['Ayurveda', 'Breathing Techniques', 'Emotional Health'],
    socials: {
      instagram: 'https://instagram.com/lakshmimenon',
      twitter: '',
      linkedin: 'https://linkedin.com/in/lakshmimenon',
      github: '',
    },
    profile_picture: profilePic,
  },
  {
    name: 'Siddharth Jain',
    category: 'TECHNOLOGY',
    company: 'AlgoLabs',
    skills: ['Algorithms', 'Competitive Programming', 'C++'],
    socials: {
      instagram: '',
      twitter: 'https://twitter.com/sidj_algo',
      linkedin: 'https://linkedin.com/in/siddjain',
      github: 'https://github.com/siddjain',
    },
    profile_picture: profilePic,
  },
  {
    name: 'Neha Malhotra',
    category: 'BUSINESS',
    company: 'BrandNest',
    skills: ['Brand Strategy', 'Digital Marketing', 'Content'],
    socials: {
      instagram: 'https://instagram.com/neham',
      twitter: '',
      linkedin: 'https://linkedin.com/in/nehamalhotra',
      github: '',
    },
    profile_picture: profilePic,
  },
  {
    name: 'Yogesh Tiwari',
    category: 'SPIRITUALITY',
    company: 'Peace Foundation',
    skills: ['Bhagavad Gita', 'Spiritual Talks', 'Life Coaching'],
    socials: {
      instagram: 'https://instagram.com/yogesh.peace',
      twitter: '',
      linkedin: '',
      github: '',
    },
    profile_picture: profilePic,
  },
  {
    name: 'Aarti Joshi',
    category: 'HEALTH & FITNESS',
    company: 'StrengthFirst',
    skills: ['Strength Training', 'Bodybuilding', 'Fitness Coaching'],
    socials: {
      instagram: 'https://instagram.com/aartistrong',
      twitter: 'https://twitter.com/aartij_fit',
      linkedin: 'https://linkedin.com/in/aartijoshi',
      github: '',
    },
    profile_picture: profilePic,
  },
  {
    name: 'Manav Kapoor',
    category: 'TECHNOLOGY',
    company: 'SecureTech',
    skills: ['Cybersecurity', 'Ethical Hacking', 'Linux'],
    socials: {
      instagram: '',
      twitter: 'https://twitter.com/manavsec',
      linkedin: 'https://linkedin.com/in/manavkapoor',
      github: 'https://github.com/manavsec',
    },
    profile_picture: profilePic,
  },
  {
    name: 'Rekha Sood',
    category: 'BUSINESS',
    company: 'GrowthMinds',
    skills: ['Business Coaching', 'Product Management', 'Pitching'],
    socials: {
      instagram: '',
      twitter: 'https://twitter.com/rekhabizcoach',
      linkedin: 'https://linkedin.com/in/rekhasood',
      github: '',
    },
    profile_picture: profilePic,
  },
  {
    name: 'Arjun Pillai',
    category: 'SPIRITUALITY',
    company: 'DivinePath',
    skills: ['Self-Enquiry', 'Bhakti Yoga', 'Peace Practices'],
    socials: {
      instagram: 'https://instagram.com/arjunspiritual',
      twitter: '',
      linkedin: '',
      github: '',
    },
    profile_picture: profilePic,
  },
];

export default LiFiMentors;
