export const sessions = [
  {
    id: 1,
    mentee: 'Alice Brown',
    type: '1:1',
    status: 'Completed',
    date: '2025-01-29T05:30:00Z', // ISO format
    email: 'alice.brown@example.com',
    topic: 'Personal Branding',
    notesResources:
      'Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.',
    file: 'Personal World.pdf',
    agenda:
      "Crafting an agenda is more than listing topics—it's about designing an experience that resonates",
    meetLink: 'https://meet.google.com',
    profileImage: '',
  },
  {
    id: 2,
    mentee: 'Bob Smith',
    type: '1:1',
    status: 'Scheduled',
    date: '2023-05-16T18:00:00Z',
    email: 'bob.smith@example.com',
    topic: 'Marketing Strategies',
    notesResources:
      'Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.',
    file: 'Personal World.pdf',
    agenda:
      "Crafting an agenda is more than listing topics—it's about designing an experience that resonates",
    meetLink: 'https://meet.google.com',
    profileImage: '',
  },
  {
    id: 3,
    mentee: 'Charlie Johnson',
    type: 'Group',
    status: 'Cancelled',
    date: '2023-05-17T11:00:00Z',
    email: 'charlie.johnson@example.com',
    topic: 'Leadership Training',
    notesResources:
      'Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.',
    file: 'Personal World.pdf',
    agenda:
      "Crafting an agenda is more than listing topics—it's about designing an experience that resonates",
    profileImage: '',
    meetLink: 'https://meet.google.com',
  },
  {
    id: 4,
    mentee: 'David Lee',
    type: '1:1',
    status: 'Completed',
    date: '2023-05-18T14:00:00Z',
    email: 'david.lee@example.com',
    topic: 'Web Development',
    notesResources:
      'Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.',
    file: 'Personal World.pdf',
    agenda:
      "Crafting an agenda is more than listing topics—it's about designing an experience that resonates",
    profileImage: '',
    meetLink: 'https://meet.google.com',
  },
  {
    id: 5,
    mentee: 'Eva Green',
    type: 'Group',
    status: 'Scheduled',
    date: '2023-05-19T16:30:00Z',
    email: 'eva.green@example.com',
    topic: 'Team Building',
    notesResources:
      'Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.',
    file: 'Personal World.pdf',
    agenda:
      "Crafting an agenda is more than listing topics—it's about designing an experience that resonates",
    profileImage: '',
    meetLink: 'https://meet.google.com',
  },
  {
    id: 6,
    mentee: 'Frank Harris',
    type: '1:1',
    status: 'Cancelled',
    date: '2023-05-20T09:00:00Z',
    email: 'frank.harris@example.com',
    topic: 'Data Science',
    notesResources:
      'Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.',
    file: 'Personal World.pdf',
    agenda:
      "Crafting an agenda is more than listing topics—it's about designing an experience that resonates",
    profileImage: '',
    meetLink: 'https://meet.google.com',
  },
  {
    id: 7,
    mentee: 'Grace Adams',
    type: 'Group',
    status: 'Completed',
    date: '2023-05-21T13:30:00Z',
    email: 'grace.adams@example.com',
    topic: 'Financial Planning',
    notesResources:
      'Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.',
    file: 'Personal World.pdf',
    agenda:
      "Crafting an agenda is more than listing topics—it's about designing an experience that resonates",
    profileImage: '',
    meetLink: 'https://meet.google.com',
  },
  {
    id: 8,
    mentee: 'Hank Roberts',
    type: '1:1',
    status: 'Scheduled',
    date: '2023-05-22T15:00:00Z',
    email: 'hank.roberts@example.com',
    topic: 'Career Coaching',
    notesResources:
      'Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.',
    file: 'Personal World.pdf',
    agenda:
      "Crafting an agenda is more than listing topics—it's about designing an experience that resonates",
    profileImage: '',
    meetLink: 'https://meet.google.com',
  },
  {
    id: 9,
    mentee: 'Ivy Walker',
    type: 'Group',
    status: 'Cancelled',
    date: '2023-05-23T10:00:00Z',
    email: 'ivy.walker@example.com',
    topic: 'Entrepreneurship',
    notesResources:
      'Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.',
    file: 'Personal World.pdf',
    agenda:
      "Crafting an agenda is more than listing topics—it's about designing an experience that resonates",
    profileImage: '',
    meetLink: 'https://meet.google.com',
  },
  {
    id: 10,
    mentee: 'Jack Young',
    type: '1:1',
    status: 'Completed',
    date: '2023-05-24T17:45:00Z',
    email: 'jack.young@example.com',
    topic: 'Personal Finance',
    notesResources:
      'Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.',
    file: 'Personal World.pdf',
    agenda:
      "Crafting an agenda is more than listing topics—it's about designing an experience that resonates",
    profileImage: '',
    meetLink: 'https://meet.google.com',
  },
  {
    id: 11,
    mentee: 'Kate Wilson',
    type: 'Group',
    status: 'Scheduled',
    date: '2023-05-25T12:00:00Z',
    email: 'kate.wilson@example.com',
    topic: 'Project Management',
    notesResources:
      'Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.',
    file: 'Personal World.pdf',
    agenda:
      "Crafting an agenda is more than listing topics—it's about designing an experience that resonates",
    profileImage: '',
    meetLink: 'https://meet.google.com',
  },
  {
    id: 12,
    mentee: 'Leo Martin',
    type: '1:1',
    status: 'Cancelled',
    date: '2023-05-26T08:30:00Z',
    email: 'leo.martin@example.com',
    topic: 'Productivity',
    notesResources:
      'Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.',
    file: 'Personal World.pdf',
    agenda:
      "Crafting an agenda is more than listing topics—it's about designing an experience that resonates",
    profileImage: '',
    meetLink: 'https://meet.google.com',
  },
  {
    id: 13,
    mentee: 'Alice Brown',
    type: '1:1',
    status: 'Completed',
    date: '2025-01-29T05:30:00Z', // ISO format
    email: 'alice.brown@example.com',
    topic: 'Personal Branding',
    notesResources:
      'Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.',
    file: 'Personal World.pdf',
    agenda:
      "Crafting an agenda is more than listing topics—it's about designing an experience that resonates",
    meetLink: 'https://meet.google.com',
    profileImage: '',
  },
  {
    id: 14,
    mentee: 'Bob Smith',
    type: '1:1',
    status: 'Scheduled',
    date: '2023-05-16T18:00:00Z',
    email: 'bob.smith@example.com',
    topic: 'Marketing Strategies',
    notesResources:
      'Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.',
    file: 'Personal World.pdf',
    agenda:
      "Crafting an agenda is more than listing topics—it's about designing an experience that resonates",
    meetLink: 'https://meet.google.com',
    profileImage: '',
  },
  {
    id: 15,
    mentee: 'Charlie Johnson',
    type: 'Group',
    status: 'Cancelled',
    date: '2023-05-17T11:00:00Z',
    email: 'charlie.johnson@example.com',
    topic: 'Leadership Training',
    notesResources:
      'Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.',
    file: 'Personal World.pdf',
    agenda:
      "Crafting an agenda is more than listing topics—it's about designing an experience that resonates",
    profileImage: '',
    meetLink: 'https://meet.google.com',
  },
  {
    id: 16,
    mentee: 'David Lee',
    type: '1:1',
    status: 'Completed',
    date: '2023-05-18T14:00:00Z',
    email: 'david.lee@example.com',
    topic: 'Web Development',
    notesResources:
      'Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.',
    file: 'Personal World.pdf',
    agenda:
      "Crafting an agenda is more than listing topics—it's about designing an experience that resonates",
    profileImage: '',
    meetLink: 'https://meet.google.com',
  },
  {
    id: 17,
    mentee: 'Eva Green',
    type: 'Group',
    status: 'Scheduled',
    date: '2023-05-19T16:30:00Z',
    email: 'eva.green@example.com',
    topic: 'Team Building',
    notesResources:
      'Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.',
    file: 'Personal World.pdf',
    agenda:
      "Crafting an agenda is more than listing topics—it's about designing an experience that resonates",
    profileImage: '',
    meetLink: 'https://meet.google.com',
  },
  {
    id: 18,
    mentee: 'Frank Harris',
    type: '1:1',
    status: 'Cancelled',
    date: '2023-05-20T09:00:00Z',
    email: 'frank.harris@example.com',
    topic: 'Data Science',
    notesResources:
      'Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.',
    file: 'Personal World.pdf',
    agenda:
      "Crafting an agenda is more than listing topics—it's about designing an experience that resonates",
    profileImage: '',
    meetLink: 'https://meet.google.com',
  },
  {
    id: 19,
    mentee: 'Grace Adams',
    type: 'Group',
    status: 'Completed',
    date: '2023-05-21T13:30:00Z',
    email: 'grace.adams@example.com',
    topic: 'Financial Planning',
    notesResources:
      'Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.',
    file: 'Personal World.pdf',
    agenda:
      "Crafting an agenda is more than listing topics—it's about designing an experience that resonates",
    profileImage: '',
    meetLink: 'https://meet.google.com',
  },
  {
    id: 20,
    mentee: 'Hank Roberts',
    type: '1:1',
    status: 'Scheduled',
    date: '2023-05-22T15:00:00Z',
    email: 'hank.roberts@example.com',
    topic: 'Career Coaching',
    notesResources:
      'Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.',
    file: 'Personal World.pdf',
    agenda:
      "Crafting an agenda is more than listing topics—it's about designing an experience that resonates",
    profileImage: '',
    meetLink: 'https://meet.google.com',
  },
  {
    id: 21,
    mentee: 'Ivy Walker',
    type: 'Group',
    status: 'Cancelled',
    date: '2023-05-23T10:00:00Z',
    email: 'ivy.walker@example.com',
    topic: 'Entrepreneurship',
    notesResources:
      'Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.',
    file: 'Personal World.pdf',
    agenda:
      "Crafting an agenda is more than listing topics—it's about designing an experience that resonates",
    profileImage: '',
    meetLink: 'https://meet.google.com',
  },
  {
    id: 22,
    mentee: 'Jack Young',
    type: '1:1',
    status: 'Completed',
    date: '2023-05-24T17:45:00Z',
    email: 'jack.young@example.com',
    topic: 'Personal Finance',
    notesResources:
      'Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.',
    file: 'Personal World.pdf',
    agenda:
      "Crafting an agenda is more than listing topics—it's about designing an experience that resonates",
    profileImage: '',
    meetLink: 'https://meet.google.com',
  },
  {
    id: 23,
    mentee: 'Kate Wilson',
    type: 'Group',
    status: 'Scheduled',
    date: '2023-05-25T12:00:00Z',
    email: 'kate.wilson@example.com',
    topic: 'Project Management',
    notesResources:
      'Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.',
    file: 'Personal World.pdf',
    agenda:
      "Crafting an agenda is more than listing topics—it's about designing an experience that resonates",
    profileImage: '',
    meetLink: 'https://meet.google.com',
  },
  {
    id: 24,
    mentee: 'Leo Martin',
    type: '1:1',
    status: 'Cancelled',
    date: '2023-05-26T08:30:00Z',
    email: 'leo.martin@example.com',
    topic: 'Productivity',
    notesResources:
      'Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique. Lorem ipsum dolor sit amet consectetur. Aliquam arcu tellus neque enim tristique.',
    file: 'Personal World.pdf',
    agenda:
      "Crafting an agenda is more than listing topics—it's about designing an experience that resonates",
    profileImage: '',
    meetLink: 'https://meet.google.com',
  },
  {
    id: 31,
    mentee: 'Amanda Johnson',
    type: '1:1',
    status: 'Pending',
    date: '2023-04-18T10:00:00Z',
    email: 'amanda.johnson@example.com',
    topic: 'Time Management',
    notesResources:
      'Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.',
    file: 'Time Management Tips.pdf',
    agenda:
      'Setting clear goals and priorities to maximize productivity and manage time effectively.',
    profileImage: '',
    meetLink: 'https://meet.google.com',
  },
  {
    id: 32,
    mentee: 'Michael Brown',
    type: '1:1',
    status: 'Pending',
    date: '2023-06-10T14:45:00Z',
    email: 'michael.brown@example.com',
    topic: 'Career Development',
    notesResources:
      'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    file: 'Career Path.pdf',
    agenda:
      'Discussing potential career paths and opportunities for professional growth and development.',
    profileImage: '',
    meetLink: 'https://meet.google.com',
  },
  {
    id: 33,
    mentee: 'Sophia Martinez',
    type: '1:1',
    status: 'Pending',
    date: '2023-07-23T09:15:00Z',
    email: 'sophia.martinez@example.com',
    topic: 'Work-Life Balance',
    notesResources:
      'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    file: 'Balance Strategies.pdf',
    agenda:
      'Exploring strategies to maintain a healthy work-life balance and prevent burnout.',
    profileImage: '',
    meetLink: 'https://meet.google.com',
  },
  {
    id: 34,
    mentee: 'David Lee',
    type: '1:1',
    status: 'Pending',
    date: '2023-08-30T11:00:00Z',
    email: 'david.lee@example.com',
    topic: 'Leadership Skills',
    notesResources:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    file: 'Leadership Guide.pdf',
    agenda:
      'Developing leadership skills to effectively manage teams and drive organizational success.',
    profileImage: '',
    meetLink: 'https://meet.google.com',
  },
  {
    id: 35,
    mentee: 'Emily Taylor',
    type: '1:1',
    status: 'Pending',
    date: '2023-09-14T13:30:00Z',
    email: 'emily.taylor@example.com',
    topic: 'Conflict Resolution',
    notesResources:
      'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    file: 'Conflict Resolution.pdf',
    agenda:
      'Learning techniques for resolving conflicts and improving communication in the workplace.',
    profileImage: '',
    meetLink: 'https://meet.google.com',
  },
];
