export const ExpertiseList = 
   [
    'JavaScript',
    'Java',
    'Python',
    'JIRA',
    'Git',
    'HTML/CSS',
    'React',
    'Node.js',
    'Docker',
    'Kubernetes',
    'Azure',
    'AWS',
    'Spring Boot',
    'Angular',
    'Vue.js',
    'Adobe Creative Suite',
    'Sketch',
    'Figma',
    'Photoshop',
    'Illustrator',
    'InDesign',
    'UI/UX Design Principles',
    'Wireframing',
    'Prototyping',
    'User Research',
    'Interaction Design',
    'Visual Design',
    'Branding',
    'Graphic Design History',
    'Typography',
    'Digital Painting',
    'Yoga',
    'Meditation',
    'Mindfulness Practices',
    'Spiritual Counseling',
    'Community Outreach',
    'Religious Education',
    'Religious Studies',
    'Yoga',
    'Meditation',
    'Squat', 'Swimming', 'Side Plank', 'Pilates', 'Cardio',
    'Financial Modeling',
    'Budgeting',
    'Forecasting',
    'Investment Analysis',
    'Portfolio Management',
    'Risk Assessment',
    'Capital Markets',
    'Derivatives',
    'Fixed Income',
    'Equity Research',
    'Valuation Techniques',
    'Corporate Finance',
    'Financial Statement Analysis',
    'Regulatory Compliance',
    'Asset Management',
  ]
