# Frontend Dockerfile
FROM node:20-alpine AS build

WORKDIR /iap-frontend
COPY package*.json /iap-frontend/
COPY .env /iap-frontend/.env
RUN npm install
COPY . /iap-frontend
RUN npm run build


# Stage 2
FROM nginx:alpine
COPY --from=build /iap-frontend/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

# Serve with nginx
# FROM nginx:alpine
# COPY --from=builder /app/dist /usr/share/nginx/html
# COPY nginx.conf /etc/nginx/nginx.conf

# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]