export const events = [
  {
    id: '1',
    title: 'SEO Optimization Strategies',
    description: 'Learn how to boost your site’s visibility using advanced SEO techniques.',
    type: '1:1',
    host: 'Alice Monroe',
    status: 'pending',
    price: '200',
    mentorName: 'Sophia Kim',
    mentorId: 'mentor-sophia-001',
    startDate: '2025-05-21',
    endDate: '2025-05-30',
    startTime: '12:00:00',
    endTime: '17:36:00',
  },
  {
    id: '2',
    title: 'Social Media Growth Hacks',
    description: 'Discover viral strategies to increase your follower count organically.',
    type: '1:N',
    price:'300',
    host: 'Brian Lee',
    status: 'live',
    mentorName: 'Liam Chen',
    mentorId: 'mentor-liam-002',
    startDate: '2025-05-29',
    endDate: '2025-06-15',
    startTime: '11:00:00',
    endTime: '15:30:00',
  },
  {
    id: '3',
    title: 'Email Campaign Fundamentals',
    description: 'Master the art of email campaigns that convert.',
    type: '1:1',
    host: 'Catherine Wells',
    status: 'completed',
    mentorName: 'Ethan Moore',
    price:'400',
    mentorId: 'mentor-ethan-003',
    startDate: '2025-06-07',
    endDate: '2025-06-07',
    startTime: '11:30:00',
    endTime: '12:30:00',
  },
  {
    id: '4',
    title: 'Content Strategy Workshop',
    description: 'Build a winning content strategy tailored to your niche.',
    type: 'Workshop',
    host: 'Diana Perez',
    price:'500',
    status: 'completed',
    mentorName: 'Ethan Moore',
    mentorId: 'mentor-ethan-003',
    startDate: '2025-06-09',
    endDate: '2025-06-15',
    startTime: '13:00:00',
    endTime: '14:00:00',
  },
  {
    id: '5',
    title: 'Influencer Marketing Tactics',
    description: 'Learn how to collaborate with influencers for better engagement.',
    type: 'Group',
    host: 'Marcus Allen',
    price:'300',
    status: 'pending',
    mentorName: 'Sophia Kim',
    mentorId: 'mentor-sophia-001',
    startDate: '2025-06-11',
    endDate: '2025-06-11',
    startTime: '15:30:00',
    endTime: '16:30:00',
  },
  {
    id: '6',
    title: 'PPC Advertising Explained',
    description: 'Explore Pay-Per-Click advertising and how to maximize ROI.',
    type: 'Workshop',
    host: 'Natalie Cho',
    price:'300',
    status: 'live',
    mentorName: 'Jordan Smith',
    mentorId: 'mentor-jordan-003',
    startDate: '2025-06-13',
    endDate: '2025-06-25',
    startTime: '16:00:00',
    endTime: '17:00:00',
  },
  {
    id: '7',
    title: 'Brand Identity Building',
    description: 'Discover how to craft and sustain a strong brand identity.',
    type: 'Group',
    host: 'Rachel Green',
    status: 'completed',
    price:'300',
    mentorName: 'Jordan Smith',
    mentorId: 'mentor-jordan-003',
    startDate: '2025-07-15',
    endDate: '2025-07-15',
    startTime: '09:00:00',
    endTime: '10:00:00',
  },
  {
    id: '8',
    title: 'Video Marketing 101',
    description: 'Learn to use video content to drive engagement and sales.',
    type: 'Workshop',
    host: 'Tom Harris',
    status: 'completed', 
    price:'700',
    mentorName: 'Maria Lopez',
    mentorId: 'mentor-maria-004',
    startDate: '2025-06-17',
    endDate: '2025-06-28',
    startTime: '12:00:00',
    endTime: '13:00:00',
  },
  {
    id: '9',
    title: 'Affiliate Marketing Essentials',
    description: 'A guide to earning income through affiliate partnerships.',
    type: 'Group',
    host: 'James Patel',
    status: 'completed',
    mentorName: 'Maria Lopez',
    mentorId: 'mentor-maria-004',
    price:'300',
    startDate: '2025-06-19',
    endDate: '2025-06-19',
    startTime: '10:00:00',
    endTime: '11:00:00',
  },
  {
    id: '10',
    title: 'Analytics & Conversion Tracking',
    description: 'Understand how to track user behavior and increase conversions.',
    type: 'Group',
    host: 'Emily Zhang',
    status: 'completed',
    mentorName: 'Maria Lopez',
    mentorId: 'mentor-maria-004',
    price:'300',
    startDate: '2025-06-21',
    endDate: '2025-06-21',
    startTime: '17:00:00',
    endTime: '18:00:00',
  },
];
